/**
 * @Project Name :  testunitnew
 * @Package Name :  selenium.test1
 * @Description :  TODO
 * @author :  liujiangbo
 * @Creation Date:  2019-11-01 22:29
 * @ModificationHistory Who    When    What
 * --------  ---------  --------------------------
 */
package selenium.test1;

/**
 * @Description  :  第一个selenium的小例子结合junit4
 * @author       :  liujiangbo
 * @Creation Date:  2019-11-01 22:29
 */

// Generated by Selenium IDE
import org.junit.After;
import org.junit.Before;
import org.junit.Test;
import org.openqa.selenium.*;
import org.openqa.selenium.chrome.ChromeDriver;
import java.util.HashMap;
import java.util.Map;

public class FirstSearchSelenium {
    private WebDriver driver;
    private Map<String, Object> vars;
    JavascriptExecutor js;
    @Before
    public void setUp() {
        driver = new ChromeDriver();
        js = (JavascriptExecutor) driver;
        vars = new HashMap<String, Object>();
    }
    @After
    public void tearDown() {
        driver.quit();
    }
    @Test
    public void search() {
        driver.get("https://testerhome.com/");
        driver.manage().window().setSize(new Dimension(1522, 816));
        driver.findElement(By.name("q")).click();
        driver.findElement(By.name("q")).sendKeys("学院");
        driver.findElement(By.name("q")).sendKeys(Keys.ENTER);
        driver.findElement(By.linkText("霍格沃兹测试学院")).click();
    }
}
